# Generated by Django 4.0 on 2021-12-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='averageNoPeople',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
