# Generated by Django 4.0 on 2021-12-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_project_averagenopeople_project_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
