# Generated by Django 4.0 on 2022-01-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_taskcomment_topiccomment_topic_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_page',
            field=models.BooleanField(default=False),
        ),
    ]
