# Generated by Django 4.0 on 2022-01-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_project_contact_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='faq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='resources',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='schema',
            field=models.BooleanField(default=False),
        ),
    ]
