# Generated by Django 4.0 on 2022-01-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('0', 'Small'), ('1', 'Medium'), ('2', 'High'), ('3', 'Urgent')], default='S', max_length=1),
        ),
    ]
