# Generated by Django 4.0 on 2022-01-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
