# Generated by Django 4.0 on 2022-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TA', 'Task Assignment'), ('TC', 'Task Assignee Change'), ('TU', 'Task Update'), ('PI', 'Project Invitation'), ('TA', 'Ticket Answer')], default='TA', max_length=2),
        ),
    ]
